apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python.library.open-webui-sqlite-migration
  title: Open WebUI sqlite migration
  description: Migration script for Open WebUI
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: production
  owner: developers
