name: Publish TechDocs

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: Digitalist-Open-Cloud/BackstageTechDocs/.github/workflows/publish-techdocs.yml@main
    with:
      entity-name: python.library.open-webui-sqlite-migration
      entity-kind: Component
      entity-namespace: default
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
